#!/usr/bin/env python
from getpass import getpass
from subprocess import call

host = "hasi.it"
ejabberctl = "/home/h42i/ejabberd/sbin/ejabberdctl"

user = input("User: ")
password = getpass("Password: ")

call([ejabberctl, "register", user, host, password])
